Traceback (most recent call last):
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/shappiron/anaconda3/envs/cba_course/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path = '.../CBC/'
files = os.listdir(path)
print(files)

data = pd.read_sas(join(path, '{}'.format(files[0])))
for file in files[1:]:
    data_new = pd.read_sas(join(path, '{}'.format(file)))
    data = pd.concat([data, data_new], ignore_index=True)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m path [38;5;241m=[39m [38;5;124m'[39m[38;5;124m.../CBC/[39m[38;5;124m'[39m
[0;32m----> 2[0m files [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mpath[49m[43m)[49m
[1;32m      3[0m [38;5;28mprint[39m(files)
[1;32m      5[0m data [38;5;241m=[39m pd[38;5;241m.[39mread_sas(join(path, [38;5;124m'[39m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(files[[38;5;241m0[39m])))

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '.../CBC/'
FileNotFoundError: [Errno 2] No such file or directory: '.../CBC/'

